### ISSUE TITLE
makeitpersonal website is inaccessible

### ISSUE THREAD

**Issue by hakerdefo** [febuiles/makeitpersonal#21]
Hi there @febuiles ,
The website [https://makeitpersonal.co/](url) can't be reached on 6:17 pm, 23 April 2020, GMT.
The error message displayed is,

> We're sorry, but something went wrong.

> The issue has been logged for investigation. Please try again later.

> Error ID: bbdef62d

> Details: Web application could not be started by the Phusion Passenger application server.

Please look into this problem.
Cheers!!!

**Comment by Kabouik** [comment]
I hope this can be fixed too!

**Comment by febuiles** [comment]
Hey!
Are you wanting access to the website or to the API?

**Comment by Kabouik** [comment]
I am trying to use cmus-lyrics, so I think in that case it is the website that is required to fetch the lyrics. See the error from cmus-lyrics below:

```
Can Not Connect To The Site "makeitpersonal"!
Make Sure Your Internet Connection Is Active!
If The Problem Persists You Can Report It At,
GitHub repository of the project by creating,
An Issue There. Here Is The Link To The Repo,

https://github.com/hakerdefo/cmus-lyrics

If you don't use GitHub you can report it by,
emailing the author at the following address,

hakerdefo (at) gmail (dot) com
```

**Comment by febuiles** [comment]
Thanks for the report friends, the API should be up and running again. 

@hakerdefo An increased amount of requests (made mostly by bots) killed the server. If this becomes an issue again I might move to an API with some type of auth. I'll create an issue in `cmus-lyrics` if that's the case.

**Comment by Kabouik** [comment]
Thanks!

**Comment by hakerdefo** [comment]
@febuiles Those :robot:
Damn them :angry:
Thanks for fixing the problem. makeitpersonal is a wonderful service I really hope you will continue to develop-support it.
It'll be great if you can let me know of any changes such as auth made to the API in future.
Cheers!!!

**Comment by hakerdefo** [comment]
@Kabouik BTW I've made a few improments to cmus-lyrics. Do check them out.
Cheers!!!
