### ISSUE TITLE
Internal server error at makeitpersnal.co

### ISSUE THREAD

**Issue by janui** [febuiles/makeitpersonal#31]
Makeitpersonal.co is throwing an internal server error, signed with: Apache/2.4.29 (Ubuntu) Server at makeitpersonal.co Port 443

It is actually returning some correct lyrics, but these are prefixed with the error message.

**Comment by febuiles** [comment]
It should be back up again, the site's being spammed and I don't have
the time to see what's up, the app hasn't been updated in a while :)
